### ISSUE TITLE
2004 Error?

### ISSUE THREAD

**Issue by tlsdlftn79** [L-Leite/cso2-master-server#108] opened 2020-05-24 17:07 UTC
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const dgram_1 = __importDefault(require("dgram"));
const net_1 = __importDefault(require("net"));
const v4_1 = __importDefault(require("uuid/v4"));
const extendedsocket_1 = require("extendedsocket");
const definitions_1 = require("packets/definitions");
const packet_1 = require("packets/in/packet");
// import { InVersionPacket } from 'packets/in/version'
const version_1 = require("packets/out/version");
const inholepunch_1 = require("packets/holepunch/inholepunch");
const outholepunch_1 = require("packets/holepunch/outholepunch");
const channelmanager_1 = require("channel/channelmanager");
const room_1 = require("room/room");
const usermanager_1 = require("user/usermanager");
const usersession_1 = require("user/usersession");
const packetlogger_1 = require("packetlogger");
/**
 * The welcome message sent to the client
 */
const clientWelcomeMessage = '~SERVERCONNECTED\n\0';
/**
 * Used to handle the server and sockets callbacks
 * It stores a list of the connected sockets
 * and a reference to our server instance
 * @class ServerManager
 */
class ServerInstance {
    static onVersionPacket(versionData, sourceConn) {
        /*const versionPacket: InVersionPacket = new InVersionPacket(versionData)
        console.log(sourceConn.uuid + ' sent a version packet. clientHash: '
            + versionPacket.clientHash)*/
        // i think the client ignores the hash string
        sourceConn.send(new version_1.OutVersionPacket(false, '6246015df9a7d1f7311f888e7e861f18'));
        return true;
    }
    /**
     * constructs our server instance
     * @param options the server options
     */
    constructor(options) {
        this.masterPort = options.portMaster;
        this.holepunchPort = options.portHolepunch;
        this.hostname = options.hostname;
        this.server = net_1.default.createServer();
        this.holepunchServer = dgram_1.default.createSocket('udp4');
        if (options.shouldLogPackets) {
            this.packetLogging = new packetlogger_1.PacketLogger();
        }
        // clean up any left over user sessions
        usersession_1.UserSession.deleteAll();
        this.server.on('connection', (socket) => {
            this.onServerConnection(socket);
        }).on('close', () => {
            this.onServerClose();
        }).on('error', (err) => {
            this.onServerError(err);
        }).on('listening', () => {
            this.onServerListening();
        });
        this.holepunchServer.on('error', (err) => {
            this.onServerError(err);
        }).on('message', (msg, rinfo) => {
            this.onHolepunchMessage(msg, rinfo);
        }).on('listening', () => {
            this.onHolepunchListening();
        });
    }
    listen() {
        this.server.listen(this.masterPort, this.hostname);
        this.holepunchServer.bind(this.holepunchPort, this.hostname);
    }
    stop() {
        return __awaiter(this, void 0, void 0, function* () {
            yield usersession_1.UserSession.deleteAll();
            this.server.close();
            process.exit(0);
        });
    }
    /**
     * Called when a new connection is created
     * @param socket - the new connection's socket
     */
    onServerConnection(socket) {
        const newConn = this.addSocket(socket);
        // welcome new connection
        newConn.write(clientWelcomeMessage);
        console.debug('new connection created, uuid ' + newConn.uuid);
        // setup socket callbacks
        newConn.on('data', (data) => {
            this.onSocketData(newConn, data);
        });
        newConn.on('error', (err) => {
            this.onSocketError(newConn, err);
        });
        newConn.on('close', (hadError) => {
            this.onSocketClose(newConn, hadError);
        });
        newConn.on('end', () => {
            this.onSocketEnd(newConn);
        });
        newConn.on('timeout', () => {
            this.onSocketTimeout(newConn);
        });
    }
    /**
     * Called when the server stops
     */
    onServerClose() {
        console.log('server closed');
        this.holepunchServer.close();
    }
    /**
     * Called when a server error occurs
     * @param err - the server error
     */
    onServerError(err) {
        console.log('server error: ' + err.message);
        throw err;
    }
    /**
     * Called when the server starts listening
     */
    onServerListening() {
        const address = this.server.address();
        console.log('server is now started listening at ' +
            address.address + ':' + address.port);
    }
    onHolepunchListening() {
        const address = this.holepunchServer.address();
        console.log('holepunch listening at ' + address.address + ':' + address.port);
    }
    /**
     * called when we receive udp holepunch info
     * @param msg the received data
     * @param rinfo the sender's info
     */
    onHolepunchMessage(msg, rinfo) {
        return __awaiter(this, void 0, void 0, function* () {
            const packet = new inholepunch_1.InHolepunchPacketUdp(msg);
            if (packet.isParsed() === false) {
                console.warn('%s sent a bad holepunch packet', rinfo.address);
                return;
            }
			if (packet.isHeartbeat()) {
            return
			}
            const session = yield usersession_1.UserSession.get(packet.userId);
            if (session == null) {
                console.warn('Couldnt\'t get user ID %i\'s session when holepunching', packet.userId);
                return;
            }
            // FIX ME: temporary workaround because Docker sets the NAT IP address when creating a session in usermanager.ts
            /*if (session.externalNet.ipAddress !== rinfo.address) {
                console.warn('Holepunch IP address is different from session\'s IP. Is someone spoofing packets?'
                    + 'userId: %i original IP: %s packet IP: %s',
                    packet.userId, session.externalNet.ipAddress, rinfo.address)
                return
            }*/
            if (session.shouldUpdatePorts(packet.portId, packet.port, rinfo.port) === false) {
                return;
            }
            session.externalNet.ipAddress = rinfo.address;
            session.internalNet.ipAddress = packet.ipAddress;
            const portIndex = session.setHolepunch(packet.portId, packet.port, rinfo.port);
            if (portIndex === -1) {
                console.warn('Unknown hole punch port');
                return;
            }
            session.update();
            const reply = new outholepunch_1.OutHolepunchPacketUdp(portIndex).build();
            this.holepunchServer.send(reply, packet.port, packet.ipAddress);
        });
    }
    /**
     * Called when a socket receives data
     * @param conn the client's socket
     * @param data the data received from the client
     */
    onSocketData(conn, data) {
        return __awaiter(this, void 0, void 0, function* () {
            // the data comes in as a string, so we need to convert it to a buffer
            const newData = Buffer.from(data, 'hex');
            // process the received data
            this.processPackets(newData, conn);
        });
    }
    processPackets(packetData, conn) {
        let curOffset = 0;
        let curTotalLen = 0;
        for (let len = packetData.length; len >= packet_1.InPacketBase.headerLength; len -= curTotalLen) {
            const pktBuffer = packetData.slice(curOffset, curOffset + len);
            const curPacket = new packet_1.InPacketBase(pktBuffer);
            const totalPktLen = curPacket.length + packet_1.InPacketBase.headerLength;
            this.onIncomingPacket(curPacket, conn);
            curTotalLen = totalPktLen;
            curOffset += totalPktLen;
        }
    }
    /**
     * hands the packet to the appropriate callback
     * @param packet the packet received from the client
     * @param connection represents a connection with the client
     * @returns true if successful, otherwise it failed
     */
    onIncomingPacket(packet, connection) {
        if (packet.isValid() === false) {
            console.warn('bad packet from ' + connection.uuid);
            return false;
        }
        if (this.packetLogging) {
            this.packetLogging.dumpIn(connection.uuid, connection.getRealSeq(), packet.id, packet.getData());
        }
        switch (packet.id) {
            case definitions_1.PacketId.Version:
                return ServerInstance.onVersionPacket(packet.getData(), connection);
            case definitions_1.PacketId.Login:
                usermanager_1.UserManager.onLoginPacket(packet.getData(), connection, this.holepunchPort);
                return true;
            case definitions_1.PacketId.RequestChannels:
                channelmanager_1.ChannelManager.onChannelListPacket(connection);
                return true;
            case definitions_1.PacketId.RequestRoomList:
                channelmanager_1.ChannelManager.onRoomListPacket(packet.getData(), connection);
                return true;
            case definitions_1.PacketId.Room:
                channelmanager_1.ChannelManager.onRoomRequest(packet.getData(), connection);
                return true;
            case definitions_1.PacketId.Host:
                usermanager_1.UserManager.onHostPacket(packet.getData(), connection);
                return true;
            case definitions_1.PacketId.Option:
                usermanager_1.UserManager.onOptionPacket(packet.getData(), connection);
                return true;
            case definitions_1.PacketId.Favorite:
                usermanager_1.UserManager.onFavoritePacket(packet.getData(), connection);
                return true;
        }
        console.warn('unknown packet id ' + packet.id + ' from ' + connection.uuid);
        return false;
    }
    /**
     * Called when a socket closes connection
     * @param conn the client's connection
     * @param hadError true if it was closed because of an error
     */
    onSocketClose(conn, hadError) {
        return __awaiter(this, void 0, void 0, function* () {
            console.log('socket ' + conn.uuid + ' closed hadError: ' + hadError);
            yield room_1.Room.cleanUpUser(conn.getOwner());
            usersession_1.UserSession.delete(conn.getOwner());
        });
    }
    /**
     * Called when a socket has an error
     * @param conn the client's connection
     * @param err the occured error
     */
    onSocketError(conn, err) {
        console.warn('socket ' + conn.uuid + ' had an error: ' + err);
    }
    /**
     * Called when a socket ends connection
     * @param conn the client's connection
     */
    onSocketEnd(conn) {
        console.log('socket ' + conn.uuid + ' ended');
    }
    /**
     * Called when a socket times out
     * @param conn the client's socket
     */
    onSocketTimeout(conn) {
        console.warn('socket ' + conn.uuid + ' timed out');
        conn.destroy(new Error('Connection timed out'));
    }
    /**
     * prepare a client's connection with a sequence number and unique id
     * and place it into the connection list
     * @param conn the client's socket
     * @returns the placed socket
     */
    addSocket(conn) {
        const newConn = extendedsocket_1.ExtendedSocket.from(conn, this.packetLogging);
        // treat data as hexadecimal
        newConn.setEncoding('hex');
        // give the connection an unique uuid
        newConn.uuid = v4_1.default();
        // init sequence number
        newConn.resetReq();
        return newConn;
    }
}
exports.ServerInstance = ServerInstance;

//# sourceMappingURL=serverinstance.js.map

**Comment by dounai2333** [comment] 2020-05-25 04:11
check https://github.com/L-Leite/cso2-master-server/issues/102#issuecomment-606693461 and https://github.com/L-Leite/cso2-master-server/issues/83.

**Comment by L-Leite** [comment] 2020-05-26 21:03
Duplicate of #83. If this issue is different from #83 please say so

**Closed by L-Leite** 2020-05-26 21:03 UTC
