### ISSUE TITLE
User Info Title Image

### ISSUE THREAD

**Issue by felixabi** [L-Leite/cso2-master-server#97] opened 2019-09-29 12:56 UTC
Bunu Nasıl Yapabilirim?

![unknown](https://user-images.githubusercontent.com/36341134/65832807-7f1a8f00-e2d1-11e9-843f-768f8d244a09.png)

**Comment by L-Leite** [comment] 2019-09-29 15:24
Duplicate of #72

**Closed by L-Leite** 2019-09-29 15:24 UTC
